In [6]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import OneHotEncoder
import pandas as pd
import tensorflow as tf

# Import our input dataset
movie_df = pd.read_csv('resource/walt_disney_movies.csv')
movie_df.head()

,Unnamed: 0,title,Production company,Country,Language,Running time,Budget,Box office,Release date,imdb,...,rotten_tomatoes,Directed by,Produced by,Based on,Starring,Music by,Distributed by,Cinematography,Edited by,Screenplay by
0,0,Academy Award Review of,Walt Disney Productions,United States,English,41.0,NaN,4.547200e+01,1937-05-19,7.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Snow White and the Seven Dwarfs,Walt Disney Productions,United States,English,83.0,1490000.0,4.180000e+08,1937-12-21,7.6,...,NaN,"['David Hand (supervising)', 'William Cottrell...",Walt Disney,"['Snow White', 'by The', 'Brothers Grimm']","['Adriana Caselotti', 'Lucille La Verne', 'Har...","['Frank Churchill', 'Paul Smith', 'Leigh Harli...",RKO Radio Pictures,NaN,NaN,NaN
2,2,Pinocchio,Walt Disney Productions,United States,English,88.0,2600000.0,1.640000e+08,1940-02-07,7.4,...,73%,"['Ben Sharpsteen', 'Hamilton Luske', 'Bill Rob...",Walt Disney,"['The Adventures of Pinocchio', 'by', 'Carlo C...","['Cliff Edwards', 'Dickie Jones', 'Christian R...","['Leigh Harline', 'Paul J. Smith']",RKO Radio Pictures,NaN,NaN,NaN
3,3,Fantasia,Walt Disney Productions,United States,English,126.0,2280000.0,8.330000e+07,1940-11-13,7.7,...,95%,"['Samuel Armstrong', 'James Algar', 'Bill Robe...","['Walt Disney', 'Ben Sharpsteen']",NaN,"['Leopold Stokowski', 'Deems Taylor']",See program,RKO Radio Pictures,James Wong Howe,NaN,NaN
4,4,The Reluctant Dragon,Walt Disney Productions,United States,English,74.0,600000.0,9.600000e+05,1941-06-20,6.9,...,68%,"['Alfred Werker', '(live action)', 'Hamilton L...",Walt Disney,NaN,"['Robert Benchley', 'Frances Gifford', 'Buddy ...","['Frank Churchill', 'Larry Morey']",RKO Radio Pictures,Bert Giennon,Paul Weatherwax,NaN

In [7]:
movie_df.tail()

,Unnamed: 0,title,Production company,Country,Language,Running time,Budget,Box office,Release date,imdb,...,rotten_tomatoes,Directed by,Produced by,Based on,Starring,Music by,Distributed by,Cinematography,Edited by,Screenplay by
439,439,The Little Mermaid,"['Walt Disney Pictures', 'Lucamar Productions'...",United States,English,NaN,NaN,NaN,NaN,7.6,...,93%,Rob Marshall,"['Rob Marshall', 'John DeLuca', 'Marc Platt', ...","['Disney', ""'s"", 'The Little Mermaid', 'by', '...","['Halle Bailey', 'Jonah Hauer-King', 'Daveed D...","['Alan Menken (score and songs)', 'Howard Ashm...","['Walt Disney Studios', 'Motion Pictures']",Dion Beebe,Wyatt Smith,"['Jane Goldman', 'David Magee']"
440,440,Peter Pan & Wendy,"['Walt Disney Pictures', 'Whitaker Entertainme...",United States,English,NaN,NaN,NaN,NaN,NaN,...,NaN,David Lowery,"['Jim Whitaker', 'Joe Roth']","[""Disney 's Peter Pan"", 'Peter and Wendy by J....","['Alexander Molony', 'Ever Anderson', 'Jude La...",NaN,Walt Disney Studios Motion Pictures,Bojan Bazelli,NaN,"['David Lowery', 'Toby Halbrooks']"
441,441,Home Alone,"['20th Century Studios', 'Hutch Parker Enterta...",United States,English,NaN,NaN,NaN,NaN,7.6,...,66%,Dan Mazer,"['Hutch Parker', 'Dan Wilson']","['Home Alone', 'by', 'John Hughes']","['Archie Yates', 'Rob Delaney', 'Ellie Kemper'...",John Debney,Disney+,Mitchell Amundsen,NaN,"['Mikey Day', 'Streeter Seidell']"
442,442,Shrunk,"['Walt Disney Pictures', 'Mandeville Films']",United States,English,NaN,NaN,NaN,NaN,NaN,...,NaN,Joe Johnston,"['David Hoberman', 'Todd Lieberman']","['Characters', 'by', 'Stuart Gordon', ',', 'Br...","['Josh Gad', 'Rick Moranis']",NaN,"['Walt Disney Studios', 'Motion Pictures']",NaN,NaN,Todd Rosenberg
443,443,Night at the Museum,"['21 Laps Entertainment', 'Ingenious Film Part...",United States,English,306.0,387000000.0,1.310000e+09,NaN,6.4,...,43%,Shawn Levy,"['Shawn Levy', 'Chris Columbus', 'Michael Barn...","['The Night at the Museum', 'by', 'Milan Trenc']","['Ben Stiller', 'Robin Williams', 'Owen Wilson...",Alan Silvestri,"['20th Century Studios', 'Disney+']",NaN,NaN,NaN

In [10]:
movie_df.keys()

Index(['Unnamed: 0', 'title', 'Production company', 'Country', 'Language',
       'Running time', 'Budget', 'Box office', 'Release date', 'imdb',
       'metascore', 'rotten_tomatoes', 'Directed by', 'Produced by',
       'Based on', 'Starring', 'Music by', 'Distributed by', 'Cinematography',
       'Edited by', 'Screenplay by'],
      dtype='object')

In [14]:
clean_movie_df = movie_df[['title','Release date','imdb', 'metascore', 'rotten_tomatoes']]

In [15]:
clean_movie_df.head()

,title,Release date,imdb,metascore,rotten_tomatoes
0,Academy Award Review of,1937-05-19,7.2,NaN,NaN
1,Snow White and the Seven Dwarfs,1937-12-21,7.6,95.0,NaN
2,Pinocchio,1940-02-07,7.4,99.0,73%
3,Fantasia,1940-11-13,7.7,96.0,95%
4,The Reluctant Dragon,1941-06-20,6.9,NaN,68%

In [17]:
clean_movie_df.isnull().sum()

title                0
Release date         9
imdb                20
metascore          151
rotten_tomatoes     53
dtype: int64

In [19]:
clean_movie_df.isna().any()[lambda x: x]

Release date       True
imdb               True
metascore          True
rotten_tomatoes    True
dtype: bool

In [24]:
clean_movie_df[clean_movie_df.isnull().any(axis=1)]

,title,Release date,imdb,metascore,rotten_tomatoes
0,Academy Award Review of,1937-05-19,7.2,NaN,NaN
1,Snow White and the Seven Dwarfs,1937-12-21,7.6,95.0,NaN
4,The Reluctant Dragon,1941-06-20,6.9,NaN,68%
7,Saludos Amigos,1942-08-24,6.1,60.0,NaN
8,Victory Through Air Power,1943-07-17,6.5,NaN,54%
...,...,...,...,...,...
439,The Little Mermaid,NaN,7.6,88.0,93%
440,Peter Pan & Wendy,NaN,NaN,NaN,NaN
441,Home Alone,NaN,7.6,63.0,66%
442,Shrunk,NaN,NaN,NaN,NaN
443,Night at the Museum,NaN,6.4,48.0,43%